# Generated by Django 3.2.8 on 2021-10-15 14:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20211015_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 15, 14, 6, 48, 364881, tzinfo=utc)),
        ),
    ]
