# Generated by Django 3.2.8 on 2021-10-16 09:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_auto_20211016_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 10, 16, 9, 45, 34, 597915, tzinfo=utc)),
        ),
    ]
